<script setup>
import { ref } from 'vue'
import { CheckCheck, Clock3, UserRoundCheck } from 'lucide-vue-next'
import { useSystemStore } from '../stores/system'
const store=useSystemStore()
const closing=ref(null), measure=ref(''), confirmClose=ref(false)
const columns=[{key:'critical',label:'严重告警',desc:'需立即响应'},{key:'major',label:'重要告警',desc:'2 小时内处理'},{key:'minor',label:'提示告警',desc:'当班确认'}]
const list=k=>store.alarms.filter(a=>a.level===k&&a.status!=='closed')
const statusLabel = status => status === 'processing' ? '处理中' : '待处理'
function openClose(alarm){closing.value=alarm;measure.value=alarm.measure||'';confirmClose.value=false}
function closeAlarm(){if(!measure.value.trim()){store.notify('请填写处理措施后才能关闭告警');return}if(!confirmClose.value){confirmClose.value=true;return}store.closeAlarm(closing.value.id,measure.value.trim());closing.value=null}
</script>
<template><div class="page-stack"><section class="workflow-strip panel"><span>处理流程</span><b>01 认领</b><i>→</i><b>02 填写处理措施</b><i>→</i><b>03 验证并关闭</b><em>待处理 {{store.alarms.filter(a=>a.status==='pending').length}} 条 · 处理中 {{store.alarms.filter(a=>a.status==='processing').length}} 条</em></section><section class="alarm-stats"><div><span class="dot critical"></span><b>{{list('critical').length}}</b><small>严重告警</small></div><div><span class="dot major"></span><b>{{list('major').length}}</b><small>重要告警</small></div><div><span class="dot minor"></span><b>{{list('minor').length}}</b><small>提示告警</small></div><div><Clock3/><b>18<em>min</em></b><small>平均响应时长</small></div></section><section class="kanban"><article v-for="col in columns" :key="col.key" class="kanban-column"><header :class="col.key"><div><strong>{{col.label}}</strong><small>{{col.desc}}</small></div><b>{{list(col.key).length}}</b></header><div class="kanban-body"><div v-for="a in list(col.key)" :key="a.id" class="alarm-card"><div class="alarm-card-top"><span>{{a.id}}</span><small>{{new Date(a.time).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}}</small></div><RouterLink :to="`/monitor/${a.deviceId}`"><h3>{{a.type}} · {{a.deviceId}}</h3></RouterLink><p>{{a.message}}</p><dl><div><dt>设备</dt><dd>{{a.deviceName}}</dd></div><div><dt>区域</dt><dd>{{a.area}}</dd></div></dl><footer v-if="a.status==='pending'"><button class="btn secondary full" @click="store.claimAlarm(a.id)"><UserRoundCheck/>认领处理</button></footer><footer v-else><span class="claimed"><i></i>{{a.owner || '当前用户'}} {{statusLabel(a.status)}}</span><button class="btn primary" @click="openClose(a)"><CheckCheck/>处理并关闭</button></footer></div><div v-if="!list(col.key).length" class="empty-state"><CheckCheck/><span>当前无此级别告警</span></div></div></article></section><div v-if="closing" class="modal-backdrop" @click.self="closing=null"><form class="modal panel" @submit.prevent="closeAlarm"><div class="modal-head"><div><small>ALARM CLOSE / {{closing.id}}</small><h2>处理并关闭告警</h2></div><button type="button" class="icon-btn" aria-label="关闭" @click="closing=null">×</button></div><p class="modal-description">{{closing.deviceId}} · {{closing.message}}</p><label>处理措施（必填）<textarea v-model="measure" rows="4" placeholder="填写现场检查、维修动作与通汽验证结果"></textarea></label><p v-if="confirmClose" class="confirm-warning">关闭后告警将进入历史记录，请再次确认处理结果。</p><div class="modal-actions"><button type="button" class="btn secondary" @click="closing=null">取消</button><button class="btn primary">{{confirmClose?'再次确认关闭':'验证并关闭告警'}}</button></div></form></div></div></template>
